apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-wait
  template:
    metadata:
      labels:
        app: curl-wait
    spec:
      containers:
        - name: curl-wait
          image: mycurl:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"