apiVersion: apps/v1
kind: Deployment
metadata:
 name: dydemo-backend
spec:
 replicas: 1
 selector:
   matchLabels:
     app: dydemo-backend
 template:
   metadata:
     labels:
       app: dydemo-backend
   spec:
     containers:
     - name: dydemo-backend-container
       image: dydemo/backend:1.0
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 5000

---
# service fronting above deployment
apiVersion: v1
kind: Service
metadata:
 name: dydemo-backend-service
spec:
 selector:
   app: dydemo-backend
 ports:
   - protocol: TCP
     port: 80
     targetPort: 5000
 type: NodePort
